version: '3'
services:
  flask-app:
    build: .
    ports:
      - "5009:5009"
    volumes:
      - ./app.py:/app/app.py
    environment:
      - FLASK_APP=app.py
    command: flask run --host=0.0.0.0 --port=5009
